apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: prd-teste
spec:
  selector:
    app: api
  ports:
  -  port: 80
     targetPort: 8080
    #  nodePort: 30080 
    #  protocol: TCP
  type: NodePort