apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstdeployment
  namespace: prd-teste
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: kubedevio/nginx-color:green