apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: prd-teste
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: fabricioveronez/pedelogo-catalogo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          envFrom:
          - configMapRef:
              name: api-configmap
          env:
            - name: Mongo_User
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: mongodb-secret
            - name: Mongo_Password
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: mongodb-secret
