apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: fabricioveronez/pedelogo-catalogo:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 32Mi
              cpu: 150m
            limits:
              memory: 64Mi
              cpu: 500m
          readinessProbe:
            httpGet:
              path: /read
              port: 80
              scheme: HTTP
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 5
          startupProbe: 
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10  
          livenessProbe:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 5
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          envFrom:
          - configMapRef:
              name: api-configmap
          env:
            - name: Mongo_User
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: mongodb-secret
            - name: Mongo_Password
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: mongodb-secret
