apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstreplicaset
  namespace: prd-teste
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-replicaset
  template:
    metadata:
      labels:
        app: nginx-replicaset
    spec:
      containers:
      - name: nginx
        image: kubedevio/nginx-color:blue